// Define your data
const subAgents = [
    { BusinessName: "139 Store", Address: "139 Neals Pen Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "19 Miles Shopping Center", Address: "19 Miles Phillip Goldson Highway", Community: "Sand Hill", District: "Belize" },
    { BusinessName: "21 Supermarket", Address: "#3256 DFC Area", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "88 Supermarket", Address: "Central American Boulevard", Community: "Belize City", District: "Belize" },
    { BusinessName: "A & G Shopping Center", Address: "29 Baymen Avenue", Community: "Belize City", District: "Belize" },
    { BusinessName: "ABC Shop", Address: "3724 Central American Boulevard", Community: "Belize City", District: "Belize" },
    { BusinessName: "Amigo Convenient Store", Address: "Front Street", Community: "Caye Caulker", District: "Belize" },
    { BusinessName: "Amigo Mini Mart", Address: "Novelo Bus Terminal", Community: "Belize City", District: "Belize" },
    { BusinessName: "Angela Hui 88", Address: "9066 Lacroix Blvd.", Community: "Belize City", District: "Belize" },
    { BusinessName: "Anya Groceries", Address: "Mahogany Heights", Community: "La Democracia", District: "Belize" },
    { BusinessName: "Arwing", Address: "24 Barbara Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "B & H Shop and Fast Food", Address: "6636 Mahogany Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Baba Grocery", Address: "5 Corner Kut & Amara Avenue", Community: "Belize City", District: "Belize" },
    { BusinessName: "Bahia Convenient Store", Address: "Bahia Area", Community: "Caye Caulker", District: "Belize" },
    { BusinessName: "Belama Best Buy", Address: "80 Albert Hoy Avenue", Community: "Belize City", District: "Belize" },
    { BusinessName: "Blue Rainbow Shop & Fast Food", Address: "74 Cemetrery Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "Bosco Supermarket", Address: "Central American Boulevard", Community: "Belize City", District: "Belize" },
    { BusinessName: "Boulevard Store", Address: "4265 Central American Blvd.", Community: "Belize City", District: "Belize" },
    { BusinessName: "Casino Tropicana Company Limited", Address: "162 Newton Barracks", Community: "Belize City", District: "Belize" },
    { BusinessName: "Caye Value Store", Address: "13 Lagoon Drive", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Chen Supermarket", Address: "3307 Central American Boulevard", Community: "Belize City", District: "Belize" },
    { BusinessName: "Chinatown Supermarket", Address: "Estrella Street", Community: "Caye Caulker", District: "Belize" },
    { BusinessName: "CK Supermarket", Address: "16 Jasmin Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Coco Store", Address: "Seagrape Drive", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "CT Mart", Address: "75 West Lake, George Price Highway", Community: "Western Paradise", District: "Belize" },
    { BusinessName: "David Supermarket", Address: "9713 La Croix Blvd.", Community: "Belize City", District: "Belize" },
    { BusinessName: "De He Li Store", Address: "38 Freetown Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "Discount Supermarket", Address: "2364 Mahogany Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "DK Supermarket", Address: "3 Miles Philip Goldson Highway", Community: "Belize City", District: "Belize" },
    { BusinessName: "Enjoy Supermarket", Address: "Front Street", Community: "Caye Caulker", District: "Belize" },
    { BusinessName: "Eric Supermarket", Address: "4 Bachelor Ave., West Landivar", Community: "Belize City", District: "Belize" },
    { BusinessName: "Everyday Supermarket & Gas Station", Address: "16 Miles George Price Highway", Community: "Hattieville", District: "Belize" },
    { BusinessName: "Fa Shop", Address: "19 Miles, Sand Hill", Community: "Sand Hill", District: "Belize" },
    { BusinessName: "Fenny Shop", Address: "114 East Canal Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Feon Shop", Address: "Youth for the Future Drive", Community: "Belize City", District: "Belize" },
    { BusinessName: "Fit Fit Shop", Address: "31 Amara Ave.", Community: "Belize City", District: "Belize" },
    { BusinessName: "Forever Fast Food", Address: "Sea Grape Drive", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Friendly Store", Address: "12 D Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Gaio Bao", Address: "46 West Collet Canal", Community: "Belize City", District: "Belize" },
    { BusinessName: "Galaxy Supermarket", Address: "178 Gwen Lizarraga Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Gaming Center Limited", Address: "Sea Star Street", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Garden Restaurant", Address: "San Pedrito Area", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Golden Sky Store", Address: "32 Cemetery Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "Good Fortune", Address: "1144 Blue Marlin Blvd.", Community: "Belize City", District: "Belize" },
    { BusinessName: "Goodwill Supermarket", Address: "2805 Central American Boulevard", Community: "Belize City", District: "Belize" },
    { BusinessName: "Guan's Shop", Address: "6 Racoon Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Helen Wu Store", Address: "#4 Y Avenue", Community: "Burrel Boom", District: "Belize" },
    { BusinessName: "Heng Loon Grocery", Address: "44 Tigris Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Henry's Bar", Address: "5 Central American Blvd.", Community: "Belize City", District: "Belize" },
    { BusinessName: "Henry's Shop", Address: "3201 Central American Boulevard", Community: "Belize City", District: "Belize" },
    { BusinessName: "Hero Grocery", Address: "San Mateo Sub Division", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Highway Store", Address: "271 Bella Vista Estate", Community: "Belize City", District: "Belize" },
    { BusinessName: "Hometown Supermarket", Address: "Sea Grape Drive", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Homever Supermarket", Address: "13 Miles Philip Goldson Highway", Community: "Ladyville", District: "Belize" },
    { BusinessName: "Ice Cold Store", Address: "Bermudian Landing Road", Community: "Burrel Boom", District: "Belize" },
    { BusinessName: "Island City Supermarket", Address: "Coconut Drive", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Island Fresh Water/Island Property Management", Address: "Bahia Puesta Del Sol", Community: "Caye Caulker", District: "Belize" },
    { BusinessName: "J & Y Shop", Address: "9073 Lacroix Blvd.", Community: "Belize City", District: "Belize" },
    { BusinessName: "J&W Shopping Mart Ltd.", Address: "22 6th Street, Kings Park", Community: "Belize City", District: "Belize" },
    { BusinessName: "J. Mall", Address: "15 Miles", Community: "Hattieville", District: "Belize" },
    { BusinessName: "Jacky's Supermarket", Address: "8 Miles George Price Highway", Community: "Western Paradise", District: "Belize" },
    { BusinessName: "Jasmin Supermarket", Address: "6413 Jasmin Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "JC Max", Address: "Avenda Mangel", Community: "Caye Caulker", District: "Belize" },
    { BusinessName: "John Supermarket", Address: "", Community: "Ladyville", District: "Belize" },
    { BusinessName: "Julie Supermarket", Address: "253 Albert Hoy Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Kelly Supermarket", Address: "DFC Area", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Key Li Imports", Address: "106 Freetown Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "Lake City Shop", Address: "", Community: "Crooked Tree", District: "Belize" },
    { BusinessName: "Lakers Mini Mart", Address: "42 Lawrence Avenue", Community: "Belize City", District: "Belize" },
    { BusinessName: "Landing Store", Address: "Bermudian Landing Village", Community: "Bermudian Landing", District: "Belize" },
    { BusinessName: "Leis Fast Food", Address: "9 Miles Philip Goldson Highway", Community: "Ladyville", District: "Belize" },
    { BusinessName: "Letto Supermarket", Address: "64 Avenida Hicaco", Community: "Caye Caulker", District: "Belize" },
    { BusinessName: "LG Store", Address: "7598 Fabers Road Extension", Community: "Belize City", District: "Belize" },
    { BusinessName: "Li Zhong Ming Shop", Address: "13 Fabers Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "Lina Supermarket", Address: "54 Mahogany Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "LK Supermarket", Address: "Bahia Puesta de Sol", Community: "Caye Caulker", District: "Belize" },
    { BusinessName: "Lord’s Bank Supermarket", Address: "26, Lords Bank Road", Community: "Ladyville", District: "Belize" },
    { BusinessName: "Lows Supermarket", Address: "8.5 miles, Philip Goldson Highway", Community: "Ladyville", District: "Belize" },
    { BusinessName: "Lucky Star 2", Address: "83 Central American Boulevard", Community: "Belize City", District: "Belize" },
    { BusinessName: "Marina Store", Address: "Seagrape Drive", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Ming Ai Supermarket", Address: "9116 Barbara Harries Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "M-Shop", Address: "2.5 miles Phillip Goldson Highway", Community: "Belize City", District: "Belize" },
    { BusinessName: "My Care", Address: "27e Downtown Plaza, Albert Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Naybaz Stores (#1733 Coney Drive)", Address: "#1733 Coney Drive", Community: "Belize City", District: "Belize" },
    { BusinessName: "Naybaz Stores (#2498 Chetumal Blvd)", Address: "#2498 Chetumal Blvd", Community: "Belize City", District: "Belize" },
    { BusinessName: "Naybaz Stores (#3129 Albert Hoy)", Address: "#3129 Albert Hoy", Community: "Belize City", District: "Belize" },
    { BusinessName: "Naybaz Stores (#37 Western Paradise)", Address: "#37 Western Paradise", Community: "Western Paradise", District: "Belize" },
    { BusinessName: "Naybaz Stores (#39 Central American Blvd.)", Address: "#39 Central American Blvd.", Community: "Belize City", District: "Belize" },
    { BusinessName: "Naybaz Stores (#428 Cemetery Road)", Address: "#428 Cemetery Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "Naybaz Stores (#43 New Road)", Address: "#43 New Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "Naybaz Stores (#46 Mahogany Street)", Address: "#46 Mahogany Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Naybaz Stores (#6120 Bay Street)", Address: "#6120 Bay Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Naybaz Stores (#72 Freetown Road)", Address: "#72 Freetown Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "Naybaz Stores (8.5 Miles, Ladyville)", Address: "Sol Gas Station - 8.5 miles Phillip Goldson Highway", Community: "Ladyville", District: "Belize" },
    { BusinessName: "Naybaz Stores (Chapoose, Caye Caulker)", Address: "Chapoose Street", Community: "Caye Caulker", District: "Belize" },
    { BusinessName: "Naybaz Stores (Laguna Drive, SP)", Address: "Laguna Drive", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Naybaz Stores (Mile 2.75, SP)", Address: "Mile 2.75", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Naybaz Stores (Mile 9.5, Ladyville)", Address: "Mile 9.5, Phillip Goldson Highway", Community: "Ladyville", District: "Belize" },
    { BusinessName: "Naybaz Stores (Pound Yard Market)", Address: "Pound Yard Market", Community: "Belize City", District: "Belize" },
    { BusinessName: "New Moon", Address: "10 miles, Philip Goldson Highway", Community: "Ladyville", District: "Belize" },
    { BusinessName: "New Road Supermarket", Address: "84 New Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "New Way Shop", Address: "3B Neals Pen Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "Ocean Supermarket", Address: "Avenida Hicaco", Community: "Caye Caulker", District: "Belize" },

    { BusinessName: "One & One Fast Food", Address: "Pescador Drive, Middle Street", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Oscar's Shop", Address: "39 Vernon Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Panda Restaurant", Address: "Middle Street", Community: "Caye Caulker", District: "Belize" },
    { BusinessName: "Paradise Supermarket", Address: "Pescador Drive", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Prime Supermarket", Address: "Front Street", Community: "Caye Caulker", District: "Belize" },
    { BusinessName: "QB Shop", Address: "91 Sylvester Boulevard", Community: "Hattieville", District: "Belize" },
    { BusinessName: "Qin Shop", Address: "36 Mahogany Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Quan Sing 2 Shop", Address: "# 9 Neal Pen Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "Richie's Supermarket", Address: "Pescador Drive", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "RJ Store", Address: "#3 Raccoon Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Sams Mini Mart", Address: "90 East Collet Canal", Community: "Belize City", District: "Belize" },
    { BusinessName: "San San Shop", Address: "7226 Caesar Ridge Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "Sanchez Shop", Address: "Maskall village", Community: "Maskall", District: "Belize" },
    { BusinessName: "Sea Horizon Ltd.", Address: "#2 Sea Grape Drive", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Sea Shore Store", Address: "2 1/2 Miles Philip Goldson", Community: "Belize City", District: "Belize" },
    { BusinessName: "Sen Sen Gaming Room", Address: "43 Daly Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Shang Ping Restaurant", Address: "107 Cemetery Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "Shun Yuan Shop", Address: "59 B, Poinsettia Street", Community: "Ladyville", District: "Belize" },
    { BusinessName: "Sky City Supermarket", Address: "8.5 miles, Philip Goldson Highway", Community: "Ladyville", District: "Belize" },
    { BusinessName: "SP Home Depot", Address: "3 Regent Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Star Hall by Jusco", Address: "2557 Central American Boulevard", Community: "Belize City", District: "Belize" },
    { BusinessName: "Sunrise Supermarket", Address: "Front Street", Community: "Caye Caulker", District: "Belize" },
    { BusinessName: "Super Sky", Address: "Avenida Longasta", Community: "Caye Caulker", District: "Belize" },
    { BusinessName: "Super Star Store", Address: "San Pedrito", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Swan Fast Food", Address: "Swan Street", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "T & W Supermarket", Address: "#44, Vernon Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Tan Kee Shop", Address: "27, George Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Tan Liang Shop", Address: "35 Fabers Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "Tans Mart", Address: "Lagoon Drive", Community: "San Pedro Town", District: "Belize" },
    { BusinessName: "Tow Tow Grocery", Address: "6772 Mahogany Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Twins Supermarket", Address: "5526 ST. Thomas Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "U 2 Shop", Address: "25 Albert Street West", Community: "Belize City", District: "Belize" },
    { BusinessName: "U Mall", Address: "9 miles, Philip Goldson Highway", Community: "Ladyville", District: "Belize" },
    { BusinessName: "Wasco Supermarket", Address: "26 South Creek Road", Community: "Belize City", District: "Belize" },
    { BusinessName: "William Supermarket", Address: "Central American Boulevard", Community: "Belize City", District: "Belize" },
    { BusinessName: "Wong's Shop", Address: "18 Miles Phillip Goldson Highway", Community: "Sand Hill", District: "Belize" },
    { BusinessName: "Yan Chen Store", Address: "", Community: "Ladyville", District: "Belize" },

    { BusinessName: "Ying Ying Shop", Address: "8227 Mahogany Street Extension", Community: "Belize City", District: "Belize" },
    { BusinessName: "Yu Store", Address: "#1 Logwood Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "Zan Zan Store", Address: "3322 Central American Boulevard", Community: "Belize City", District: "Belize" },
    { BusinessName: "Zhong Wang Shop", Address: "#6 Kings Park Street", Community: "Belize City", District: "Belize" },
    { BusinessName: "1+1 Supermarket", Address: "Racoon Ave.", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "1688 Shopping Center", Address: "2 Mahogany St.", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "28 Supermarket", Address: "Bullet Tree Road", Community: "Bullet Tree Falls", District: "Cayo" },
    { BusinessName: "8&8 Supermarket", Address: "Bishop Martin", Community: "Santa Elena Town", District: "Cayo" },
    { BusinessName: "A&8 Store", Address: "Bradleys Bank Area", Community: "Santa Elena Town", District: "Cayo" },
    { BusinessName: "A&N Supermarket", Address: "109 George Price Highway", Community: "Santa Elena Town", District: "Cayo" },
    { BusinessName: "ABC Supermarket", Address: "Bullet Tree Road", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Alex Store", Address: "George Price Blvd.", Community: "Benque Viejo del Carmen Town", District: "Cayo" },
    { BusinessName: "Alwin's Super Store", Address: "6 Almond Blvd.", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Anna Supermarket", Address: "70 George Price Highway", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Anthony's Supermarket", Address: "George Price Highway", Community: "Santa Elena Town", District: "Cayo" },
    { BusinessName: "ATM Supermarket", Address: "", Community: "Teakettle", District: "Cayo" },
    { BusinessName: "Ba Sheng Lun Supermarket", Address: "4415 Nim Li Punit Street", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Brothers Supermarket", Address: "George Price Highway", Community: "Santa Elena Town", District: "Cayo" },
    { BusinessName: "Cardinal Hardware", Address: "34 Cardinal Ave.", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Carrefour Store", Address: "3662 Citron Street", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Chen's Store", Address: "#25 Joseph Andrew Drive", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Chen's Super Market", Address: "", Community: "Bullet Tree Falls", District: "Cayo" },
    { BusinessName: "China Town Shop", Address: "92 George Price Highway", Community: "Santa Elena Town", District: "Cayo" },
    { BusinessName: "Chuc Service Station Ltd.", Address: "1/2 Mile Benque Road", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "CIB Cayo", Address: "#13 Stannton Street", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "City Corner Supermarket", Address: "Joseph Andrew Drive", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Dairy Store", Address: "6129 Racoon Ave.", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Daisy's Store", Address: "George Price Blvd.", Community: "Benque Viejo del Carmen Town", District: "Cayo" },
    { BusinessName: "David Restaurant", Address: "#102 Benque Viejo Rd.", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "De Xin Store", Address: "George Price Blvd.", Community: "Benque Viejo del Carmen Town", District: "Cayo" },
    { BusinessName: "Double M Store", Address: "", Community: "Benque Viejo del Carmen Town", District: "Cayo" },
    { BusinessName: "Fangs Store", Address: "Camalote Village", Community: "Camalote", District: "Cayo" },
    { BusinessName: "Fansico Supermarket", Address: "15 Nimli Punit Street", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Father Supermarket", Address: "Market Square", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Franco's Store", Address: "", Community: "Camalote", District: "Cayo" },
    { BusinessName: "Good Time Shop - San Ignacio", Address: "Trench Town", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Good Time Shop - Santa Familia", Address: "", Community: "Santa Familia", District: "Cayo" },
    { BusinessName: "H&D Shop", Address: "", Community: "Unitedville", District: "Cayo" },
    { BusinessName: "Helen Snack Shop", Address: "2 St. Martin Ave.", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Helen Supermarket", Address: "Benque Road", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Highway Supermarket", Address: "21 George Price Highway", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Hot Summer Store", Address: "#13 Burns Ave.", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Hua Young Super Store", Address: "", Community: "San Jose Succotz", District: "Cayo" },
    { BusinessName: "Huang Mart", Address: "2 Constitution Drive", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Ionni Store", Address: "#2 Summit Street", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "J&A Store", Address: "#21 Flamingo Ave.", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Jack Store", Address: "Nim Li Punit Street", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "James Shopping Center", Address: "2200 San Martin Ave.", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Jimmy First Step", Address: "St. Margaret Village", Community: "7miles/siete millas/El Progresso", District: "Cayo" },
    { BusinessName: "Joe Store", Address: "Roaring Creek", Community: "Roaring Creek", District: "Cayo" },
    { BusinessName: "Katy's Shop", Address: "92 San Martin Avenue", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Li Store", Address: "", Community: "Esperanza", District: "Cayo" },
    { BusinessName: "Lin's Supermarket", Address: "164 George Price", Community: "Santa Elena Town", District: "Cayo" },
    { BusinessName: "Love Town", Address: "Savannah Street", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Lu Store", Address: "Santa Cruz", Community: "Benque Viejo del Carmen Town", District: "Cayo" },
    { BusinessName: "Lucky Store", Address: "Roaring Creek", Community: "Roaring Creek", District: "Cayo" },
    { BusinessName: "M&J Shopping Center", Address: "Hummingbird Highway", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "M&Y Shopping Center", Address: "7 San Martin Street", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Max Super Store", Address: "", Community: "Bullet Tree Falls", District: "Cayo" },
    { BusinessName: "Maya Mopan Store", Address: "Maya Mopan Street", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Mini Store", Address: "37 Kennedy St.", Community: "Benque Viejo del Carmen Town", District: "Cayo" },
    { BusinessName: "Naybaz (10 Roaring Creek, Cayo)", Address: "#10 Roaring Creek", Community: "Roaring Creek", District: "Cayo" },
    { BusinessName: "Naybaz (3rd Street, Cayo)", Address: "3rdt Street", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Naybaz (51 St Matthew St, Belmopan)", Address: "#51 St. Matthew St.", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Naybaz (Bradley's Bank, Cayo)", Address: "Bradley's Bank", Community: "Santa Elena Town", District: "Cayo" },
    { BusinessName: "Naybaz (Camalote St, Cayo)", Address: "Camalote Street", Community: "Bullet Tree Falls", District: "Cayo" },
    { BusinessName: "Naybaz (Church St, Succotz)", Address: "Church Street", Community: "San Jose Succotz", District: "Cayo" },
    { BusinessName: "Naybaz (Georgeville,Cayo)", Address: "Georgeville Village", Community: "Georgeville", District: "Cayo" },
    { BusinessName: "Naybaz (Santa Familia Rd, Cayo)", Address: "Santa Familia Road", Community: "Santa Familia", District: "Cayo" },
    { BusinessName: "Naybaz (St Joseph St, Benque)", Address: "St. Joseph Street", Community: "Benque Viejo del Carmen Town", District: "Cayo" },
    { BusinessName: "Naybaz (Uno San Ignacio)", Address: "Benque Rd.", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Naybaz (Uruguay St, Belmopan", Address: "Uruguay Street", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Naybaz (Young Bank, Cayo)", Address: "Young Bank", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "New B2", Address: "82 Bullet Tree Rd", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "New Taisan Shop", Address: "Kiskadee Street", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "New World Restaurant", Address: "Constitution Drive", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Ontario Store", Address: "", Community: "Ontario", District: "Cayo" },
    { BusinessName: "Panda Online", Address: "7 Savannah Street", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Panda Online SE", Address: "George Price Highway", Community: "Santa Elena Town", District: "Cayo" },
    { BusinessName: "Payless Store", Address: "Salvapan Street", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Ping Store", Address: "Saint Margaret's Village", Community: "St. Margaret", District: "Cayo" },
    { BusinessName: "Princess International San Ignacio Ltd.", Address: "18 Buena Vista Street", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Puma ShangHai", Address: "54 Hummingbird Highway", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Quan Ji Shop", Address: "#5 Santa Maria Street", Community: "Santa Elena Town", District: "Cayo" },
    { BusinessName: "Rainbow Super Store", Address: "3034 Forest Drive", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Red Coral Store", Address: "1900 Constitution Drive", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Sansco Supermarket", Address: "George Price Highway", Community: "Santa Elena Town", District: "Cayo" },
    { BusinessName: "Suny Side", Address: "Roaring Creek", Community: "Roaring Creek", District: "Cayo" },
    { BusinessName: "Super J Shop", Address: "", Community: "Teakettle", District: "Cayo" },
    { BusinessName: "Super Q Mart", Address: "83 Bullet Tree Rd", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Super Y Mart", Address: "94 Bullet Tree Rd.", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Tai San Shop", Address: "#15 Burns Avenue", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Tan Store", Address: "", Community: "Valley of Peace", District: "Cayo" },
    { BusinessName: "Tim's Store", Address: "20 Bullet Tree Rd.", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Tin Store", Address: "Roaring Creek Village", Community: "Roaring Creek", District: "Cayo" },
    { BusinessName: "TJ Supermarket", Address: "3654 Citron Street", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Uncle Store", Address: "", Community: "Cotton Tree", District: "Cayo" },
    { BusinessName: "Uncle Supermarket", Address: "Hummingbird Avenue", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "VIP Lily", Address: "Thornley St.", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "We Shop", Address: "Buena Vista", Community: "San Ignacio Town", District: "Cayo" },
    { BusinessName: "Wei Li Shop", Address: "", Community: "Belmopan City", District: "Cayo" },
    { BusinessName: "Xu Store", Address: "Churchill Street", Community: "Benque Viejo del Carmen Town", District: "Cayo" },
    { BusinessName: "Yi Long Store", Address: "Unitedville Village", Community: "Unitedville", District: "Cayo" },
    { BusinessName: "Yoila's Super Store", Address: "", Community: "Armenia", District: "Cayo" },
    { BusinessName: "Yongxing Store", Address: "", Community: "Armenia", District: "Cayo" },
    { BusinessName: "Zhen's Supermarket", Address: "38 George Price Blvd.", Community: "Benque Viejo del Carmen Town", District: "Cayo" },

    { BusinessName: "24/7 Gas Station", Address: "Ranchito Village", Community: "Ranchito", District: "Corozal" },
    { BusinessName: "A&A Loza Store", Address: "", Community: "Patchakan", District: "Corozal" },
    { BusinessName: "AEME'S", Address: "3rd Street South", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Annie Wu", Address: "3rd Avenue", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Ban Store", Address: "Santa Elena Rd.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Benzer International Co. Ltd.", Address: "Corozal Free Zone", Community: "Corozal Free Zone", District: "Corozal" },
    { BusinessName: "Calcutta Community Supermarket", Address: "", Community: "Calcutta", District: "Corozal" },
    { BusinessName: "Camry Co. Ltd", Address: "#1 North Plaza", Community: "Corozal Free Zone", District: "Corozal" },
    { BusinessName: "Chang Fa Store", Address: "Park St North", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Chang Sang Supermarket", Address: "3rd Street South", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Circle K Supermarket", Address: "#25 6th St South", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Corozal Chan's Supermarket", Address: "#7 Park Street South", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "D& L Supermarket", Address: "6th St, 6th Ave.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Da Chong Shop", Address: "", Community: "Sarteneja", District: "Corozal" },
    { BusinessName: "Delia Shop", Address: "", Community: "Xaibe", District: "Corozal" },
    { BusinessName: "Dengs Supermarket", Address: "19th 7th Avenue", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Ding Feng Store", Address: "", Community: "San Narciso", District: "Corozal" },
    { BusinessName: "Dragon Hardware & Bicycle Shop", Address: "#33 7th Ave.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "E Loza Store", Address: "", Community: "Patchakan", District: "Corozal" },
    { BusinessName: "Elsira Yadira Florez", Address: "", Community: "Progresso", District: "Corozal" },
    { BusinessName: "Espinoza's Shop", Address: "", Community: "Chan Chen", District: "Corozal" },
    { BusinessName: "Everyday Supermarket - San Joaquin", Address: "", Community: "San Joaquin", District: "Corozal" },
    { BusinessName: "Frys Store", Address: "#9 Santa Rita Rd.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Gallito Supermarket", Address: "2nd St South", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Guo Tai Supermarket", Address: "7th Ave.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Happy Family Supermarket", Address: "", Community: "San Joaquin", District: "Corozal" },
    { BusinessName: "Henry's Supermarket", Address: "3rd Street South", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Home Best Shop", Address: "7th Ave.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Huan Huan Supermarket", Address: "#52 3rd St. South", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "J Mart Store", Address: "", Community: "San Joaquin", District: "Corozal" },
    { BusinessName: "Jesusita Melanie Garcia", Address: "", Community: "Louisville", District: "Corozal" },
    { BusinessName: "Jing Jing Supermarket", Address: "53 Santa Elena Rd.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Kelly Supermarket", Address: "Sarteneja Village", Community: "Sarteneja", District: "Corozal" },
    { BusinessName: "Kenny Shop", Address: "", Community: "Xaibe", District: "Corozal" },
    { BusinessName: "Lets Go Supermarket", Address: "5th Avenue", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Lily Chen", Address: "Corozal Rd.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Lucky One Plus One Shop", Address: "", Community: "Concepcion", District: "Corozal" },
    { BusinessName: "Luna Grocery Store", Address: "Chula Vista", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Marissa Nazira Flores", Address: "", Community: "Copper Bank", District: "Corozal" },
    { BusinessName: "Maxs Chen Supermarket", Address: "", Community: "Altamira", District: "Corozal" },
    { BusinessName: "Mei Chen Shop", Address: "", Community: "Caledonia", District: "Corozal" },
    { BusinessName: "Merly's Shop", Address: "", Community: "San Victor", District: "Corozal" },
    { BusinessName: "Naybaz (4th Ave, Corozal)", Address: "#4 4th Avenue", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Naybaz (Altamira, Corozal)", Address: "#18 Altamira", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Naybaz (Olga Marin Dr., Corozal)", Address: "#12 Olga Marin Drive", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Naybaz (Port Saul St, Corozal)", Address: "#69 Port Saul St.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Naybaz (San Joaquin, Corozal)", Address: "Mile 78 San Joaquin", Community: "San Joaquin", District: "Corozal" },
    { BusinessName: "Naybaz (San Roman, Corozal)", Address: "#45 San Roman Blvd.", Community: "San Roman", District: "Corozal" },
    { BusinessName: "Naybaz (Santa Rita Rd, Corozal)", Address: "#13 Santa Rita Rd.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Nelsie Nelina Chan", Address: "", Community: "San Narciso", District: "Corozal" },
    { BusinessName: "New Bridge Supermarket", Address: "91 7th Ave.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "New Town Hardware", Address: "7th Avenue", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "New World Store", Address: "53 7th Avenue", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "One Mall", Address: "", Community: "Ranchito", District: "Corozal" },
    { BusinessName: "P.R. Lin and Sons", Address: "", Community: "Xaibe", District: "Corozal" },
    { BusinessName: "Parkway City", Address: "1st Street North", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Rainbow One Supermarket", Address: "3rd Street South 4th Ave.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Rainbow Town Supermarket", Address: "5th Street North", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "RJV'S Grocery Store", Address: "Altamira Rd.", Community: "Altamira", District: "Corozal" },
    { BusinessName: "Rong' Supermarket", Address: "4th Ave.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Rufo's Store", Address: "", Community: "Xaibe", District: "Corozal" },
    { BusinessName: "Salome Cunil", Address: "", Community: "Buena Vista", District: "Corozal" },
    { BusinessName: "San Store", Address: "#87 1st St. South", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Season Supermarket", Address: "#125 5th Avenue", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Summer Holiday Store", Address: "Corozal Town", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Tangs Supermarket", Address: "Santa Rita Rd.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Timpol Store & Bakery", Address: "#84 4th Ave.", Community: "Corozal Town", District: "Corozal" },
    { BusinessName: "Tommy Store", Address: "", Community: "Cristo Rey", District: "Corozal" },
    { BusinessName: "TRISHIK International", Address: "Corozal Free Zone", Community: "Corozal Free Zone", District: "Corozal" },
    { BusinessName: "Vaule Supermarket", Address: "", Community: "San Roman", District: "Corozal" },
    { BusinessName: "Z-One Store", Address: "San Andres Village", Community: "San Andres", District: "Corozal" },
    { BusinessName: "7 Eleven Store", Address: "Benque Viejo Street", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Ahorra Mas Supermarket", Address: "Cinderella Street", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Angie's Mini Mart", Address: "San Jose Village", Community: "San Jose", District: "Orange Walk" },
    { BusinessName: "Armando Babb", Address: "5 San Francisco Street", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Aron Supermarket", Address: "Belize Corozal Road", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "August Super Store", Address: "", Community: "August Pine Ridge", District: "Orange Walk" },
    { BusinessName: "Baili Store", Address: "Guinea Grass Village", Community: "Guinea Grass", District: "Orange Walk" },
    { BusinessName: "C.Y. Shop", Address: "", Community: "Trial Farm", District: "Orange Walk" },
    { BusinessName: "Carmelita Supermarket", Address: "", Community: "Carmelita", District: "Orange Walk" },
    { BusinessName: "Chen Hardware Store", Address: "5 Zericote Street", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Dave's Store", Address: "Palma Boundary Road", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Dickerson Family Mart", Address: "Belize Corozal Road", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Dickerson Supermarket", Address: "Cinderella Street", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Estefany Sea Food", Address: "Belize Corozal Rd", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Ester Shop", Address: "", Community: "August Pine Ridge", District: "Orange Walk" },
    { BusinessName: "Fung Wu San", Address: "Queen Victoria Avenue", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Harry's Store", Address: "Orange Walk Town", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Hong Li Shop", Address: "Otro Benque Road", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Hui Shuang Shop", Address: "San Andres Street", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Juan Carlos Urizar", Address: "Trial Farm Village", Community: "Trial Farm", District: "Orange Walk" },
    { BusinessName: "Kai & A Cafe", Address: "28 Northern Highway", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Lala Store", Address: "", Community: "San Estevan", District: "Orange Walk" },
    { BusinessName: "Laly's Boledo", Address: "14 San Victor St.", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Luda Fast Food", Address: "Belize Corozal Road", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Luda Supermarket", Address: "Otro Benque Road", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Maria Calles", Address: "", Community: "San Pablo", District: "Orange Walk" },
    { BusinessName: "Maria E. Castillo", Address: "", Community: "San Estevan", District: "Orange Walk" },
    { BusinessName: "Maricela Castillo", Address: "", Community: "San Estevan", District: "Orange Walk" },
    { BusinessName: "Miguel Choto", Address: "Late Street", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Nancy Cardona", Address: "Audinette Alley", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Naybaz (Guinea Grass, Orange Walk)", Address: "#373 Posito Rd.", Community: "Guinea Grass", District: "Orange Walk" },
    { BusinessName: "Naybaz (Palmar Rd, Orange Walk)", Address: "#3982 Palmar Rd.", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Naybaz (Progress St, Orange Walk)", Address: "#19 Progress St", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Naybaz (San Antonio Rd, Orange Walk)", Address: "#24 San Antonio Rd.", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Naybaz (Santa Ana St, Orange Walk)", Address: "#4312 Santa Ana St.", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "New Taisan", Address: "38 Louisana Area", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Olga Cabañas", Address: "", Community: "San Lazaro", District: "Orange Walk" },
    { BusinessName: "Pancha", Address: "46 Otro Benque Road", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Philip Lee", Address: "Progress Street", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Ramon Norberto Babb", Address: "2 Park Street", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Raul Magana", Address: "", Community: "San Felipe", District: "Orange Walk" },
    { BusinessName: "Resource Supermarket", Address: "Northern Highway", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Ring Store", Address: "Liberty Ave.", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Roberto Torres", Address: "Chan Pine Ridge Village", Community: "Chan Pine Ridge", District: "Orange Walk" },
    { BusinessName: "Rowena Ke", Address: "Yo Creek Village", Community: "Yo Creek", District: "Orange Walk" },
    { BusinessName: "Royal Fashion", Address: "Queen Victoria Avenue", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Sarita Cruz", Address: "San Felipe Village", Community: "San Felipe", District: "Orange Walk" },
    { BusinessName: "Semrain Padwani", Address: "Belize Corozal Rd.", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Shen's Shop", Address: "", Community: "San Jose", District: "Orange Walk" },
    { BusinessName: "Sun Lock Shop", Address: "19 Zericote Street", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Sunny's Store", Address: "Bakers Street", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Sunrise Store", Address: "Otro Benque Road", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Tan Ji Shop", Address: "", Community: "Trial Farm", District: "Orange Walk" },
    { BusinessName: "Trinidad Store", Address: "", Community: "Trinidad", District: "Orange Walk" },
    { BusinessName: "Winne Restaurant", Address: "", Community: "Guinea Grass", District: "Orange Walk" },
    { BusinessName: "Zhen Zhen Shop", Address: "", Community: "Guinea Grass", District: "Orange Walk" },
    { BusinessName: "Zhi Store", Address: "Queen Victoria Avenue", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "Gas Plus Gas Station", Address: "1412 San Antonio Rd", Community: "Orange Walk Town", District: "Orange Walk" },
    { BusinessName: "5 Star Supermarket", Address: "", Community: "Santa Cruz", District: "Stann Creek" },
    { BusinessName: "9 and 9 Store", Address: "", Community: "Placencia", District: "Stann Creek" },
    { BusinessName: "All In One", Address: "Fadden Avenue", Community: "Independence/Mango Creek", District: "Stann Creek" },
    { BusinessName: "Ashton Shopping Center", Address: "", Community: "Seine Bight", District: "Stann Creek" },
    { BusinessName: "B&G", Address: "", Community: "Hopkins", District: "Stann Creek" },
    { BusinessName: "Benguche Store", Address: "Pen Road 1058", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Best Buy Supermarket", Address: "126 Commerce St.", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Best Choice Supermarket", Address: "Fadden Avenue", Community: "Independence/Mango Creek", District: "Stann Creek" },
    { BusinessName: "Bob Shopping Center", Address: "", Community: "San Juan", District: "Stann Creek" },
    { BusinessName: "Coco Supermarket", Address: "", Community: "San Roman", District: "Stann Creek" },
    { BusinessName: "DaYang Shop", Address: "1474 George Price Drive", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Dong Lee Shop", Address: "", Community: "Hopkins", District: "Stann Creek" },
    { BusinessName: "Everyday Supermarket - Placencia", Address: "", Community: "Placencia", District: "Stann Creek" },
    { BusinessName: "Fi We Mart", Address: "#76", Community: "Hopkins", District: "Stann Creek" },
    { BusinessName: "First Choice Supermarket", Address: "#2 Vincent St.", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Garden Store", Address: "#58 Vincent St.", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Happy Shopping Center", Address: "", Community: "Hopkins", District: "Stann Creek" },
    { BusinessName: "Harlem Super Store", Address: "42 Commerce St.", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Havana Supermarket", Address: "Dangriga Town", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Hin Kee Store", Address: "#73 Commerce St.", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Hope Creek Supermarket", Address: "", Community: "Hope Creek", District: "Stann Creek" },
    { BusinessName: "Huang Chen Supermarket (A)", Address: "", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Huang Chen Supermarket (B)", Address: "", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Huang Chen Supermarket (C)", Address: "", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "J&J Superstore", Address: "Main Road", Community: "Cowpen", District: "Stann Creek" },
    { BusinessName: "Jian Store", Address: "#69 Fadden Avenue", Community: "Independence/Mango Creek", District: "Stann Creek" },
    { BusinessName: "J-Mart", Address: "8 St. Havana St.", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Jun's Super Store", Address: "195 King St.", Community: "Independence/Mango Creek", District: "Stann Creek" },
    { BusinessName: "Kalin Store", Address: "", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "King Star", Address: "45 Per Rd.", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "LaLa Supermarket", Address: "", Community: "Santa Cruz", District: "Stann Creek" },
    { BusinessName: "Li Jiang Store", Address: "Amado Mena Street", Community: "Independence/Mango Creek", District: "Stann Creek" },
    { BusinessName: "Lu Kee Store", Address: "", Community: "Independence/Mango Creek", District: "Stann Creek" },
    { BusinessName: "Mai 2 Store", Address: "", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Me and You Store", Address: "", Community: "Seine Bight", District: "Stann Creek" },
    { BusinessName: "Merry Super Store", Address: "", Community: "Silk Grass", District: "Stann Creek" },
    { BusinessName: "Naybaz (2959 Yampi St, Dangriga)", Address: "#2959 Yampi St.", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Naybaz (41 Pen Road, Dangriga)", Address: "#41 Pen Road", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Naybaz (61 Hopkins Rd, Hopkins)", Address: "#61 Hopkins Rd.", Community: "Hopkins", District: "Stann Creek" },
    { BusinessName: "Naybaz (George Price Dr, Dangriga)", Address: "Mile 1 George Price Dr.", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Naybaz (Hope Creek Village)", Address: "Lot #100 Hope Creek Village", Community: "Hope Creek", District: "Stann Creek" },
    { BusinessName: "Naybaz (Howard St, Dangriga)", Address: "#907 Howard St.", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Naybaz (Pomona Village)", Address: "Pomona Village", Community: "Pomona", District: "Stann Creek" },
    { BusinessName: "Naybaz (Santa Cruz, Stann Creek)", Address: "Lot #4 Santa Cruz Village", Community: "Santa Cruz", District: "Stann Creek" },
    { BusinessName: "Naybaz (Silk Grass Village)", Address: "Lot #262 Silk Grass Village", Community: "Silk Grass", District: "Stann Creek" },
    { BusinessName: "New Site Supermarket", Address: "", Community: "Independence/Mango Creek", District: "Stann Creek" },
    { BusinessName: "Pomona Shopping Mall", Address: "", Community: "Pomona", District: "Stann Creek" },
    { BusinessName: "Qingji Shop", Address: "", Community: "Hope Creek", District: "Stann Creek" },
    { BusinessName: "San Roman Family Shopping Center", Address: "", Community: "San Roman", District: "Stann Creek" },
    { BusinessName: "Sea Side Supermarket", Address: "Main Street", Community: "Placencia", District: "Stann Creek" },
    { BusinessName: "Silk Grass One Stop", Address: "", Community: "Silk Grass", District: "Stann Creek" },
    { BusinessName: "T-Box Store", Address: "#94 Commerce Street", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "The Price Is Right Supermarket", Address: "", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Tienda La Confianza", Address: "", Community: "Silk Grass", District: "Stann Creek" },
    { BusinessName: "Village Store", Address: "", Community: "Hopkins", District: "Stann Creek" },
    { BusinessName: "Wendy Store", Address: "Amido Mena Ave.", Community: "Independence/Mango Creek", District: "Stann Creek" },
    { BusinessName: "Xian Dali Store", Address: "", Community: "Dangriga Town", District: "Stann Creek" },
    { BusinessName: "Yong Huang Supermarket", Address: "", Community: "Sittee River", District: "Stann Creek" },
    { BusinessName: "87 Store", Address: "", Community: "Bella Vista", District: "Toledo" },
    { BusinessName: "A&A Supermarket", Address: "", Community: "Bella Vista", District: "Toledo" },
    { BusinessName: "BJ Store", Address: "#29 George St.", Community: "Punta Gorda Town", District: "Toledo" },
    { BusinessName: "Hou's Supermarket", Address: "", Community: "Bella Vista", District: "Toledo" },
    { BusinessName: "Indian Ville Shopping Center", Address: "Cayo Street", Community: "Punta Gorda Town", District: "Toledo" },
    { BusinessName: "James Yao Shop", Address: "71 Jose Maria Nunez Street", Community: "Punta Gorda Town", District: "Toledo" },
    { BusinessName: "Kapok (Brads) Store", Address: "50 Main Middle St.", Community: "Punta Gorda Town", District: "Toledo" },
    { BusinessName: "Laughing Supermarket", Address: "40 West St.", Community: "Punta Gorda Town", District: "Toledo" },
    { BusinessName: "Mayday Store", Address: "Jose Maria St.", Community: "Punta Gorda Town", District: "Toledo" },
    { BusinessName: "Ming Yang Shop", Address: "#35 George Price St.", Community: "Punta Gorda Town", District: "Toledo" },
    { BusinessName: "Miss Kim Store", Address: "", Community: "Bella Vista", District: "Toledo" },
    { BusinessName: "Naybaz (Bella Vista, Toledo)", Address: "Mile 43 Southern Highway", Community: "Bella Vista", District: "Toledo" },
    { BusinessName: "Naybaz (Indianville, Toledo)", Address: "15 Cayo St, Indianville", Community: "Punta Gorda Town", District: "Toledo" },
    { BusinessName: "Neighbourhood Store", Address: "Wild Can St.", Community: "Hopeville", District: "Toledo" },
    { BusinessName: "New Beginning Shopping Center", Address: "", Community: "Santa Cruz", District: "Toledo" },
    { BusinessName: "Ok Grocery Shop", Address: "#9 North St.", Community: "Punta Gorda Town", District: "Toledo" },
    { BusinessName: "T&Z Supermarket", Address: "", Community: "Bella Vista", District: "Toledo" },
    { BusinessName: "Tim's Shopping Center", Address: "#26 George Price St.", Community: "Punta Gorda Town", District: "Toledo" }

];

// Export the data
export { subAgents };